name: RewardTransfer
main: me.LegendsMC.RewardTransfer.RewardTransfer
description: RewardTransfer Plugin!
version: 1
commands:
   RewardTransfer:
      aliases: [rt]
      description: Reward Transfer.